### ISSUE TITLE
Cancel GPS Goal if new goal comes in

### ISSUE THREAD

**Issue by vinnnyr** [ros-agriculture/mobile_robot_sim#6]

**Comment by mturktest123** [comment]
Vinny - on this issue there probably needs to be a flag indicating if the new waypoint should be immediate or added to the end of the current sequence? I can easily imagine either scenario.



On Jul 2, 2020, at 9:00 PM, Vinny Ruia <notifications@github.com> wrote:

﻿

**Comment by vinnnyr** [comment]
I can imagine both, but I was more thinking of an “override”.  This may end up being the default behavior, but I like the ability of having a “queued” waypoint system that might be optional.

I plan to implement behaviortee to define missions (for the most basic mission, have a series of N waypoints to be autonomously navigated to)
